"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['CatDV Quick Search.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    name='CatDV Quick Search',
    description='Find clips stored on the CatDV database',
    version='1.0.1.4',
    date='19-Jun-2015',
    author='Edson Cudjoe',
    author_email='e.cudjoe@hotmail.co.uk',
    url='https://github.com/edsoncudjoe',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
